require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  Exclude:
    - 'bin/*'
    - 'vendor/**/*'

  NewCops: enable

Layout/LineLength:
  Max: 120
  AllowedPatterns: ['(\s*)# '] # Ignore lines with comments
  Exclude:
    - 'spec/**/*'

RSpec:
  Language:
    Includes:
      Examples:
        - run_test! # rswag tests use `run_test!` as examples and without this rubocop will create RSpec/EmptyExampleGroup violations

RSpec/MultipleExpectations:
  Enabled: true
  Max: 15

Style/ClassVars:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/HashSyntax:
  Enabled: false
